version: '3'

services:
  revproxy:
    restart: always
    build: ./revproxy
    ports:
      - "80:80"
    links:
      - api:api

  api:
    restart: always
    volumes:
      - "/tmp:/tmp"
    build:
      context: ../../
      args:
        INCLUDE_UWSGI: 'true'
    environment:
      EXAMPLE_API_REVERSE_PROXY_SETUP: 'true'
      FLASK_CONFIG: 'production'
    command: 'uwsgi --need-app --manage-script-name --mount /=app:create_app() --uwsgi-socket 0.0.0.0:5000 --enable-threads --logger file:logfile=/tmp/flask-stack2.log,maxsize=104857600'
